name: seita
phase: constrainer

target:
  _target_: trainers.const_trainer.Trainer
  dim: 64
  delta_t: 0.1
  traj_len: 50
  dec_layers: 2
  drop_path: 0.2
  dyn_loss_rate: 0.3
  pretrained_weights: ${pretrained_weights}
  lr: ${lr}
  weight_decay: ${weight_decay}
  epochs: ${epochs}
  warmup_epochs: ${warmup_epochs}
