name: seita
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - default
dependencies:
  - python=3.10.14
  - matplotlib=3.5.3
  - pandas=2.2.2
  - scipy=1.14.0
  - seaborn=0.13.2
  # - tensorboard=2.17.0
  # - tensorboardX=2.6.2.2
  # - tensorflow=2.17.0
  # - tensorflow-estimator=2.15.0
  - pyquaternion=0.9.9
  - pytest=8.3.1
  - orjson=3.10.6
  - ncls=0.0.68
  - dill=0.3.8
  - tqdm=4.66.4
  - notebook=7.2.1
  - scikit-learn=1.5.1
  - opencv-python=4.10.0.84
  - pyswarms=1.3.0
  - ray=2.33.0 
  - timm=1.0.8
  - wandb=0.13.5
  - hydra-core=1.2.0
  - pip
  - pip:
    - -i https://pypi.tuna.tsinghua.edu.cn/simple 
